moonstuff/urls.py
from django.conf.urls import url

from . import views

app_name = 'moonstuff'

urlpatterns = [
    url(r'^$', views.moon_index, name='moon_index'),
    url(r'^add/$', views.add_token, name='add_token'),
    url(r'^moon/(?P<moonid>[0-9]+)/$', views.moon_info, name='moon_info'),
    url(r'^moon/scan/$', views.moon_scan, name='moon_scan'),
    url(r'^list/$', views.moon_list, name='moon_list'),
]

moonstuff/models.py
from django.db import models
from allianceauth.eveonline.models import EveCorporationInfo, EveCharacter


# Create your models here.
class Ore(models.Model):
    group_id = models.IntegerField()
    group_name = models.CharField(max_length=255)
    ore_name = models.CharField(max_length=75)
    ore_id = models.IntegerField(primary_key=True)
    unit_value = models.FloatField(null=True)
    volume = models.FloatField(null=True)

    def __str__(self):
        return "{} - {}".format(self.group_name, self.ore_name)


class Resource(models.Model):
    ore = models.CharField(max_length=75)
    ore_id = models.ForeignKey(Ore, on_delete=models.DO_NOTHING)
    amount = models.DecimalField(max_digits=11, decimal_places=10)

    def __str__(self):
        return "{} - {}".format(self.ore, self.amount)

    class Meta:
        unique_together = (('amount', 'ore_id'),)


class Moon(models.Model):
    name = models.CharField(max_length=80)
    system_id = models.IntegerField()
    moon_id = models.IntegerField()
    resources = models.ManyToManyField(Resource)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_moonstuff', 'Can access the moonstuff module.'),
        )


def get_fallback_moon():
    return Moon.objects.get_or_create(system_id=30000142, moon_id=40009087)


class Refinery(models.Model):
    name = models.CharField(max_length=150)
    structure_id = models.CharField(max_length=15)
    size = models.BooleanField()
    location = models.ForeignKey(Moon, on_delete=models.SET(get_fallback_moon))
    owner = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE)

    @property
    def size_to_string(self):
        if self.size is True:
            return "Large"
        else:
            return "Medium"

    def __str__(self):
        return self.name


class ExtractEvent(models.Model):
    start_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    decay_time = models.DateTimeField()
    structure = models.ForeignKey(Refinery, on_delete=models.CASCADE)
    moon = models.ForeignKey(Moon, on_delete=models.CASCADE)
    corp = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('arrival_time', 'moon'),)

    def __str__(self):
        return "{} - {}".format(self.moon.name, self.arrival_time)


class MoonDataCharacter(models.Model):
    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE)
    latest_notification = models.BigIntegerField(null=True, default=0)

moonstuff/templates/moonstuff/add_scan.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Moon Utilities' %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'moonstuff/moonmenu.html' %}
        <h2> {% trans "Moon Scan Input" %} </h2>
        <p class="lead">Use the below form to input moonscans. You can input as many as you want.</p>

        <div class="col-md-12">
            <div class="row">
                <form class="form-signin" role="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" name="scan" rows="10" id="scan" required></textarea>
                    </div>
                    <br />
                    <button class="btn btn-primary btn-block" type="submit" name="submit_scan" id="submit_scan">Submit Moon Scans</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

moonstuff/templates/moonstuff/moon_index.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Moon Utilities' %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'moonstuff/moonmenu.html' %}
        <ul class="nav nav-pills">
            <li class="active"><a data-toggle="tab" href="#upcoming"> Upcoming Extractions</a></li>
            <li><a data-toggle="tab" href="#recent"> Recent Extractions</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active panel-default" id="upcoming">
                <div class="panel-body">
                    <h2> {% trans "Upcoming Extractions" %} </h2>
                    <p class="lead">All times displayed are EVE/UTC</p>
                    {% if exts|length_is:"0" %}
                        <div class="alert alert-warning" role="alert">
                            <p> There are no extractions happening in the next 7 days.</p>
                        </div>
                    {% else %}
                    <table class="table table-striped" id="table_upcoming">
                        <thead>
                            <th>Moon</th>
                            <th>Arrival Time</th>
                            <th></th>
                        </thead>
                        <tbody>
                            {% for event in exts %}
                                <tr>
                                    <td>{{ event.moon.name }}</td>
                                    <td>{{ event.arrival_time }}</td>
                                    <td><a class="btn btn-primary btn-sm" href="{% url 'moonstuff:moon_info' event.moon.moon_id %}"><span class="fa fa-eye fa-fw"></span></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
            <div class="tab-pane fade active panel-default" id="recent">
                <div class="panel-body">
                    <h2> {% trans "Recent Extractions" %} </h2>
                    <p class="lead">All times displayed are EVE/UTC</p>
                    {% if r_exts|length_is:"0" %}
                        <div class="alert alert-warning" role="alert">
                            <p> There are no extractions happening in the next 7 days.</p>
                        </div>
                    {% else %}
                    <table class="table table-striped" id="table_recent">
                        <thead>
                            <th>Moon</th>
                            <th>Arrival Time</th>
                            <th></th>
                        </thead>
                        <tbody>
                            {% for event in r_exts %}
                                <tr>
                                    <td>{{ event.moon.name }}</td>
                                    <td>{{ event.arrival_time }}</td>
                                    <td><a class="btn btn-primary btn-sm" href="{% url 'moonstuff:moon_info' event.moon.moon_id %}"><span class="fa fa-eye fa-fw"></span></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}
{% block extra_script %}
    $(document).ready(function(){
        $('#table_recent').DataTable();
        $('#table_upcoming').DataTable();
    });
{% endblock %}

moonstuff/templates/moonstuff/moon_info.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load humanize %}
{% block page_title %}{% trans 'Moon Info' %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'moonstuff/moonmenu.html' %}
        <h2> {% trans "Moon Information" %} - {{ moon.name }} </h2>
        <div class="row">
            <div class="col-md-6  mr-md-1">
                <div class="panel panel-success">
                    <div class="panel-heading text-center">
                        <h3 class="panel-title"> Moon Resource Information </h3>
                    </div>
                    <div class="panel-body">
                        {% if res|length_is:"0" %}
                            <div class="alert alert-warning">
                                <p> There are no resources recorded for {{ moon.name }}. {% if perms.moonstuff.add_moon %} Why not add a moon scan? {% endif %}</p>
                            </div>
                        {% else %}
                            {% for res in res %}
                                <ul class="media-list">
                                    <li class="media">
                                        <div class="media-left">
                                            <img class="media-object" src="{{ res.1 }}">
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">{{ res.0 }}</h4>
                                            <div class="progress" style="height: 20px;">
                                                <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="{{ res.2 }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ res.2 }}%; line-height: 20px;">
                                                    <span class="sr-only">{{ res.2 }}% {{ res.0 }}</span>
                                                    <h5 class="media-heading" style="padding-top: 2px">{{ res.2 }}%</h5>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% if not res|length_is:"0" and perms.add_resource %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Moon Value
                    </div>
                    <div class="panel-body">
                        <input id="days" data-slider-id='ex1Slider' type="range" data-slider-min="1" data-slider-max="30" data-slider-step="1" data-slider-value="30"/>
                        <br />
                        <span>Value for a <span id="daysVal">30</span> day pull: <strong><span id="pullVal">{{ value_per_month|floatformat:2|intcomma }}</span></strong></span>
                    </div>
                    <div class="panel-footer">
                        Note: Value calculated based on max refine in a T2 Athanor located in NullSec.
                    </div>
                </div>
            {% endif %}
            </div>
            <div class="col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading text-center">
                        <h3 class="panel-title"> Next Pulls </h3>
                    </div>
                    <div class="panel-body">
                        <table class="table" style="text-align: center">
                            <thead>
                                <th style="text-align: center"> Date(EVE/UTC)</th>
                            </thead>
                            <tbody>
                                {% if pulls|length_is:"0" %}
                                    <tr>
                                        <td> No Pulls for this moon in the next month.</td>
                                    </tr>
                                {% else %}
                                    {% for pull in pulls %}
                                        <tr>
                                            <td>{{ pull.arrival_time }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading text-center">
                        <h3 class="panel-title"> Past Pulls</h3>
                    </div>
                    <div class="panel-body">
                        <table class="table text-center" id="past-events">
                            <thead>
                                <th> Date (EVE/UTC) </th>
                            </thead>
                            <tbody>
                                {% if ppulls|length_is:"0" %}
                                    <tr>
                                        <td> No Past Pulls recorded for this moon.</td>
                                    </tr>
                                {% else %}
                                    {% for pull in ppulls %}
                                        <tr>
                                            <td>{{ pull.arrival_time }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}
{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/bootstrap-slider.js" integrity="sha256-59/apVFrosMLFX2dHZLGvb3nPpu7e0Yx1rsDr1dTRrk=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
{% endblock %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/css/bootstrap-slider.css" />
{% endblock %}
{% block extra_script %}
    $(document).ready(function(){
        $('#past-events').DataTable();
        $('#days').slider();
        $('#days').on("slide", function(slideEvt){$('#daysVal').text(slideEvt.value); $('#pullVal').text(numeral(slideEvt.value * {{ value_per_day }}).format('0,0.00'));});
    });
{% endblock %}

moonstuff/templates/moonstuff/moonmenu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'moonstuff:moon_index' %}">{% trans "Moons" %}</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="{% navactive request 'moonstuff:moon_list' %}"><a href="{% url 'moonstuff:moon_list' %}">List Moons</a> </li>
            {% if perms.moonstuff.add_resource %}
            <li class="{% navactive request 'moonstuff:moon_scan' %}"> <a href="{% url 'moonstuff:moon_scan' %}">Add Moon Scan</a></li>
            {% endif %}
        </ul>
        {% if perms.moonstuff.add_extractevent %}
        <a class="btn btn-success navbar-btn" style="float: right" href="{% url 'moonstuff:add_token' %}"><span class="fa fa-plus fa-fw"></span></a>
        {% endif %}
    </div>
</div>
</nav>